import { createClient } from '@supabase/supabase-js'

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || ''
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || ''

if (!supabaseUrl || !supabaseAnonKey) {
  console.warn('Supabase credentials not found. Using local mode.')
}

export const supabase = createClient(supabaseUrl, supabaseAnonKey, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true,
  },
})

// Database types (will be auto-generated by Supabase CLI in production)
export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string
          email: string
          created_at: string
          preferred_language: 'nl' | 'en'
        }
        Insert: {
          id: string
          email: string
          created_at?: string
          preferred_language?: 'nl' | 'en'
        }
        Update: {
          id?: string
          email?: string
          created_at?: string
          preferred_language?: 'nl' | 'en'
        }
      }
      user_state: {
        Row: {
          id: string
          user_id: string
          state: any // JSONB
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          state: any
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          state?: any
          updated_at?: string
        }
      }
      events: {
        Row: {
          id: string
          user_id: string
          event_type: string
          timestamp: string
          metadata: any // JSONB
        }
        Insert: {
          id?: string
          user_id: string
          event_type: string
          timestamp?: string
          metadata?: any
        }
        Update: {
          id?: string
          user_id?: string
          event_type?: string
          timestamp?: string
          metadata?: any
        }
      }
    }
  }
}
