import { createClient } from '@supabase/supabase-js'

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || ''
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || ''

const isValidUrl = (() => {
  try {
    if (!supabaseUrl) return false
    new URL(supabaseUrl)
    return true
  } catch {
    return false
  }
})()

export const isSupabaseConfigured = Boolean(supabaseUrl && supabaseAnonKey && isValidUrl)

if (!isSupabaseConfigured) {
  console.warn('Supabase credentials missing or invalid. Running in local mode.')
}

export const supabaseStatus = {
  dbUnavailable: false,
}

export function setGlobalDbUnavailable(value: boolean) {
  supabaseStatus.dbUnavailable = value
  if (typeof window !== 'undefined') {
    window.dispatchEvent(
      new CustomEvent('supabase:dbUnavailable', { detail: { value } })
    )
  }
}

export const supabase = createClient(supabaseUrl, supabaseAnonKey, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true,
  },
})

// Database types (will be auto-generated by Supabase CLI in production)
export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string
          email: string
          created_at: string
          preferred_language: 'nl' | 'en'
        }
        Insert: {
          id: string
          email: string
          created_at?: string
          preferred_language?: 'nl' | 'en'
        }
        Update: {
          id?: string
          email?: string
          created_at?: string
          preferred_language?: 'nl' | 'en'
        }
      }
      user_state: {
        Row: {
          id: string
          user_id: string
          state: any // JSONB
          version: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          state: any
          version?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          state?: any
          version?: number
          created_at?: string
          updated_at?: string
        }
      }
      events: {
        Row: {
          id: string
          user_id: string
          type: string
          metadata: any // JSONB
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          type: string
          metadata?: any
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          type?: string
          metadata?: any
          created_at?: string
        }
      }
      push_subscriptions: {
        Row: {
          id: string
          user_id: string
          endpoint: string
          p256dh: string
          auth: string
          user_agent: string | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          endpoint: string
          p256dh: string
          auth: string
          user_agent?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          endpoint?: string
          p256dh?: string
          auth?: string
          user_agent?: string | null
          created_at?: string
        }
      }
    }
  }
}
