import { createClient } from '@supabase/supabase-js'

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || ''
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || ''

const isValidUrl = (() => {
  try {
    if (!supabaseUrl) return false
    new URL(supabaseUrl)
    return true
  } catch {
    return false
  }
})()

export const isSupabaseConfigured = Boolean(supabaseUrl && supabaseAnonKey && isValidUrl)

if (!isSupabaseConfigured) {
  console.warn('Supabase credentials missing or invalid. Running in local mode.')
}

export const supabaseStatus = {
  dbUnavailable: false,
}

export function setGlobalDbUnavailable(value: boolean) {
  supabaseStatus.dbUnavailable = value
  if (typeof window !== 'undefined') {
    window.dispatchEvent(
      new CustomEvent('supabase:dbUnavailable', { detail: { value } })
    )
  }
}

export const supabase = createClient(supabaseUrl, supabaseAnonKey, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true,
  },
})

// Database types (will be auto-generated by Supabase CLI in production)
export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string
          email: string | null
          created_at: string
          preferred_language: 'nl' | 'en'
        }
        Insert: {
          id: string
          email?: string | null
          created_at?: string
          preferred_language?: 'nl' | 'en'
        }
        Update: {
          id?: string
          email?: string | null
          created_at?: string
          preferred_language?: 'nl' | 'en'
        }
      }
      user_state: {
        Row: {
          id: string
          user_id: string
          state: unknown // JSONB
          version: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          state: unknown
          version?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          state?: unknown
          version?: number
          created_at?: string
          updated_at?: string
        }
      }
      events: {
        Row: {
          id: string
          user_id: string
          type: string
          metadata: unknown // JSONB
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          type: string
          metadata?: unknown
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          type?: string
          metadata?: unknown
          created_at?: string
        }
      }
      push_subscriptions: {
        Row: {
          id: string
          user_id: string
          endpoint: string
          p256dh: string
          auth: string
          user_agent: string | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          endpoint: string
          p256dh: string
          auth: string
          user_agent?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          endpoint?: string
          p256dh?: string
          auth?: string
          user_agent?: string | null
          created_at?: string
        }
      }
      integrations: {
        Row: {
          id: string
          user_id: string
          provider: string
          status: string
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          provider: string
          status?: string
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          provider?: string
          status?: string
          created_at?: string
        }
      }
      calendar_sources: {
        Row: {
          id: string
          user_id: string
          name: string
          ics_url: string | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          name: string
          ics_url?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          name?: string
          ics_url?: string | null
          created_at?: string
        }
      }
      assessments: {
        Row: {
          id: string
          user_id: string
          course: string
          item: string
          score: number | null
          weight: number | null
          assessed_at: string | null
          status: string
          block_id: string | null
          source: string
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          course: string
          item: string
          score?: number | null
          weight?: number | null
          assessed_at?: string | null
          status?: string
          block_id?: string | null
          source?: string
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          course?: string
          item?: string
          score?: number | null
          weight?: number | null
          assessed_at?: string | null
          status?: string
          block_id?: string | null
          source?: string
          created_at?: string
        }
      }
      lti_launches: {
        Row: {
          id: string
          user_id: string | null
          issuer: string
          deployment_id: string | null
          context: unknown
          created_at: string
        }
        Insert: {
          id?: string
          user_id?: string | null
          issuer: string
          deployment_id?: string | null
          context?: unknown
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string | null
          issuer?: string
          deployment_id?: string | null
          context?: unknown
          created_at?: string
        }
      }
      courses: {
        Row: {
          id: string
          user_id: string
          lti_context_id: string | null
          title: string
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          lti_context_id?: string | null
          title: string
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          lti_context_id?: string | null
          title?: string
          created_at?: string
        }
      }
      deadlines: {
        Row: {
          id: string
          user_id: string
          title: string
          due_at: string
          status: string
          source: string
          course_id: string | null
          course_name: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          title: string
          due_at: string
          status?: string
          source: string
          course_id?: string | null
          course_name?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          title?: string
          due_at?: string
          status?: string
          source?: string
          course_id?: string | null
          course_name?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      grades: {
        Row: {
          id: string
          user_id: string
          course_id: string
          course_name: string | null
          current_score: number | null
          predicted_score: number | null
          required_score: number | null
          source: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          course_id: string
          course_name?: string | null
          current_score?: number | null
          predicted_score?: number | null
          required_score?: number | null
          source: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          course_id?: string
          course_name?: string | null
          current_score?: number | null
          predicted_score?: number | null
          required_score?: number | null
          source?: string
          updated_at?: string
        }
      }
    }
  }
}
